package com.erp.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class ResetController {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PostMapping("/reset")
    @ResponseBody
    public String resetDatabase() {
        try {
            String sql = "TRUNCATE TABLE employees CASCADE; " +
                         "TRUNCATE TABLE products CASCADE; " +
                         "TRUNCATE TABLE orders CASCADE; " +
                         "TRUNCATE TABLE order_item CASCADE; " +
                         "TRUNCATE TABLE inventory CASCADE; " +
                         "ALTER TABLE orders MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1); " +
                         "ALTER TABLE order_item MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);";
            jdbcTemplate.execute(sql);
            return "Database reset successfully!";
        } catch (Exception e) {
            return "Error resetting database: " + e.getMessage();
        }
    }
}
